# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Code Deployment Pipeline

on:
  push:
    branches: [ main ]

# Global environment variables for all jobs
env:
  AWS_REGION: us-east-2
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  SERVICES: cartservice,checkoutservice,currencyservice,emailservice,frontend,productcatalogservice,recommendationservice,shippingservice
  EKS_CLUSTER: 818n-g21-eks
  K8S_NAMESPACE: 818n-g21-ns

jobs:
  # Build and publish container images for all services
  build_images:
    uses: ./.github/workflows/component-build-images.yml
    secrets: inherit
    with:
      aws-region: $AWS_REGION
      ecr-registry: $ECR_REGISTRY
      services: $SERVICES
      push: true

  # Run integration and policy checks
#   integration_checks:
#     needs: build_images
#     uses: ./.github/workflows/checks.yml
#     secrets: inherit

  # Deploy to Kubernetes via Helm
  kubernetes_deployment:
    # needs: integration_checks
    uses: ./.github/workflows/k8s-deployment.yml
    secrets: inherit
    with:
      aws-region: $AWS_REGION
      cluster-name: $K8S_NAMESPACE
      namespace: $K8S_NAMESPACE
      ecr-registry: $ECR_REGISTRY
      services: $SERVICES
      chart: open-telemetry/opentelemetry-demo
      release-name: otel-demo
